version: "3"

services:
  alice-bitcoind:
    container_name: alice-bitcoind
    restart: always
    image: btcpayserver/bitcoin:0.18.0
    expose:
    - "8335"
    - "39389"
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        rpcport=8335
        rpcbind=0.0.0.0:8335
        port=39389
        addnode=bob-bitcoind:39388
    volumes:
    - "alice_bitcoind_data:/data"

  bob-bitcoind:
    container_name: bob-bitcoind
    restart: always
    image: btcpayserver/bitcoin:0.18.0
    expose:
    - "8336"
    - "39388"
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        rpcport=8336
        rpcbind=0.0.0.0:8336
        port=39388
        addnode=alice-bitcoind:39389
    volumes:
    - "bob_bitcoind_data:/data"

  cli:
    container_name: cli
    restart: always
    image: btcpayserver/bitcoin:0.18.0
    environment:
      BITCOIN_NETWORK: regtest
    volumes:
      - "cli_data:/data"
      - "alice_bitcoind_data:/alice/bitcoind"
      - "bob_bitcoind_data:/bob/bitcoind"
    links:
      - alice-bitcoind
      - bob-bitcoind

  alice-ln:
    image: elementsproject/lightningd
    container_name: alice-ln
    command:
      - --bitcoin-rpcconnect=alice-bitcoind:8335
      - --network=regtest
      - --alias=alice-ln
      - --log-level=debug      
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9735:9735"
    volumes:
      - "alice_ln_datadir:/root/.lightning"
      - "alice_bitcoind_data:/root/.bitcoin"
    links:
      - alice-bitcoind

  bob-ln:
    image: elementsproject/lightningd
    container_name: bob-ln
    command:
      - --bitcoin-rpcconnect=bob-bitcoind:8336
      - --network=regtest
      - --alias=bob-ln
      - --log-level=debug      
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9736"
    ports:
      - "0.0.0.0:9736:9736"
    volumes:
      - "bob_ln_datadir:/root/.lightning"
      - "bob_bitcoind_data:/root/.bitcoin"
    links:
      - alice-bitcoind

volumes:
  alice_bitcoind_data:
  bob_bitcoind_data:
  alice_ln_datadir:
  bob_ln_datadir:
  cli_data:

networks: {}